# render.yaml - Infraestructura como Código (Versión con Estructura Corregida)

# Versión del blueprint de Render
version: 1

# ESTRUCTURA CORRECTA: 'databases' está fuera de 'services'
databases:
  # --- Base de Datos PostgreSQL para n8n ---
  - name: n8n-database
    plan: free
    postgresMajorVersion: 14
    region: ohio # Elige la región más cercana a ti o a tus clientes.

services:
  # --- Servicio 1: n8n (El Cerebro de la Automatización) ---
  - type: web
    name: n8n-main
    runtime: docker
    image:
      url: n8n-io/n8n:latest
    plan: starter # Se recomienda el plan 'starter' para n8n. Puedes empezar con 'free'.
    healthCheckPath: /healthz
    envVars:
      # --- Configuración de la Base de Datos ---
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromDatabase: # CORRECCIÓN: Se usa 'fromDatabase' para referenciar la base de datos
          name: n8n-database
          property: host
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n-database
          property: port
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-database
          property: database
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-database
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-database
          property: password
      
      # --- Configuración General de n8n ---
      - key: GENERIC_TIMEZONE
        value: America/Guayaquil
      - key: N8N_HOST
        value: ${RENDER_EXTERNAL_URL}
      - key: WEBHOOK_URL
        value: ${RENDER_EXTERNAL_URL}

  # --- Servicio 2: Evolution API (El Puente con WhatsApp) ---
  - type: web
    name: evolution-api
    runtime: docker
    image:
      url: atende/evolution-api:latest
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: CREATE_INSTANCE
        value: "false"

      # --- Variables de Autenticación y Conexión de Evolution API ---
      - key: AUTHENTICATION_API_KEY
        generateValue: true
      - key: DATABASE_ENABLED
        value: "false"
      
      # --- Configuración de Webhooks (para que Evolution hable con n8n) ---
      - key: WH_EVENT_MESSAGE
        value: "true"
      - key: WH_EVENT_CONNECTION
        value: "true"
      
      # --- ¡IMPORTANTE! DEBES CONFIGURAR ESTAS VARIABLES MÁS TARDE ---
      - key: FACEBOOK_APP_ID
        sync: false
      - key: FACEBOOK_APP_SECRET
        sync: false
      - key: FACEBOOK_WEBHOOK_VERIFY_TOKEN
        generateValue: true